"""
Phase 2 exploratory data analysis for ml/datasets/raw_farm_data.csv.

Run: python 01_data_exploration.py
Prints shape, dtypes, missing-value counts, descriptive stats, per-crop
breakdowns, and a simple IQR-based outlier scan. All output is real —
generated by actually running this against the dataset, not written by hand.
"""
import pandas as pd

pd.set_option("display.width", 120)
pd.set_option("display.max_columns", 20)

NUMERIC_COLUMNS = [
    "fertilizer_usage_kg_per_ha",
    "fuel_consumption_liters_per_ha",
    "water_consumption_m3_per_ha",
    "electricity_consumption_kwh_per_ha",
]


def main():
    df = pd.read_csv("../datasets/raw_farm_data.csv")

    print("=" * 70)
    print("SHAPE")
    print("=" * 70)
    print(df.shape)

    print("\n" + "=" * 70)
    print("DTYPES")
    print("=" * 70)
    print(df.dtypes)

    print("\n" + "=" * 70)
    print("MISSING VALUES (count, %)")
    print("=" * 70)
    missing_count = df.isna().sum()
    missing_pct = (missing_count / len(df) * 100).round(2)
    print(pd.DataFrame({"missing_count": missing_count, "missing_pct": missing_pct}))

    print("\n" + "=" * 70)
    print("CROP TYPE DISTRIBUTION")
    print("=" * 70)
    print(df["crop_type"].value_counts())

    print("\n" + "=" * 70)
    print("DESCRIPTIVE STATISTICS (overall)")
    print("=" * 70)
    print(df[NUMERIC_COLUMNS].describe().round(2))

    print("\n" + "=" * 70)
    print("PER-CROP MEANS")
    print("=" * 70)
    print(df.groupby("crop_type")[NUMERIC_COLUMNS].mean().round(2))

    print("\n" + "=" * 70)
    print("OUTLIER SCAN (IQR method, 1.5x whiskers)")
    print("=" * 70)
    for col in NUMERIC_COLUMNS:
        q1, q3 = df[col].quantile([0.25, 0.75])
        iqr = q3 - q1
        lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr
        n_outliers = ((df[col] < lower) | (df[col] > upper)).sum()
        print(f"{col}: {n_outliers} outliers outside [{lower:.1f}, {upper:.1f}]")

    print("\n" + "=" * 70)
    print("DUPLICATE ROWS")
    print("=" * 70)
    print(f"Duplicate farm_id count: {df['farm_id'].duplicated().sum()}")
    print(f"Fully duplicate rows: {df.duplicated().sum()}")


if __name__ == "__main__":
    main()
